async function init() {
  canvas = document.getElementById("canvas");

  await document.fonts.load("32px Boogaloo");
  console.log("Font Boogaloo loaded ✅");

  const assets = [
    "assets/img/background/layers/clouds/one.png",
    "assets/img/background/layers/clouds/two.png",
    "assets/img/background/layers/clouds/full.png",
    "assets/img/background/layers/firstLayer/one.png",
    "assets/img/background/layers/firstLayer/two.png",
    "assets/img/background/layers/firstLayer/full.png",
    "assets/img/background/layers/secondLayer/one.png",
    "assets/img/background/layers/secondLayer/two.png",
    "assets/img/background/layers/secondLayer/full.png",
    "assets/img/background/layers/thirdLayer/one.png",
    "assets/img/background/layers/thirdLayer/two.png",
    "assets/img/background/layers/thirdLayer/full.png",
    "assets/img/background/layers/air.png",
    "assets/img/background/completeBackground.png",
    "assets/img/background/firstHalfBackground.png",
    "assets/img/background/secondHalfBackground.png",
    "assets/img/characterPepe/dead/dFiftyOne.png",
    "assets/img/characterPepe/dead/dFiftyTwo.png",
    "assets/img/characterPepe/dead/dFiftyThree.png",
    "assets/img/characterPepe/dead/dFiftyFour.png",
    "assets/img/characterPepe/dead/dFiftyFive.png",
    "assets/img/characterPepe/dead/dFiftySix.png",
    "assets/img/characterPepe/dead/dFiftySeven.png",
    "assets/img/characterPepe/hurt/hFortyOne.png",
    "assets/img/characterPepe/hurt/hFortyTwo.png",
    "assets/img/characterPepe/hurt/hFortyThree.png",
    "assets/img/characterPepe/idle/idle/iOne.png",
    "assets/img/characterPepe/idle/idle/iTwo.png",
    "assets/img/characterPepe/idle/idle/iThree.png",
    "assets/img/characterPepe/idle/idle/iFour.png",
    "assets/img/characterPepe/idle/idle/iFive.png",
    "assets/img/characterPepe/idle/idle/iSix.png",
    "assets/img/characterPepe/idle/idle/iSeven.png",
    "assets/img/characterPepe/idle/idle/iEight.png",
    "assets/img/characterPepe/idle/idle/iNine.png",
    "assets/img/characterPepe/idle/idle/iTen.png",
    "assets/img/characterPepe/idle/longIdle/iEleven.png",
    "assets/img/characterPepe/idle/longIdle/iTwelve.png",
    "assets/img/characterPepe/idle/longIdle/iThirteen.png",
    "assets/img/characterPepe/idle/longIdle/iFourteen.png",
    "assets/img/characterPepe/idle/longIdle/iFifteen.png",
    "assets/img/characterPepe/idle/longIdle/iSixteen.png",
    "assets/img/characterPepe/idle/longIdle/iSeventeen.png",
    "assets/img/characterPepe/idle/longIdle/iEighteen.png",
    "assets/img/characterPepe/idle/longIdle/iNineteen.png",
    "assets/img/characterPepe/idle/longIdle/iTwenty.png",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ];

  try {
    await AssetManager.loadAll(assets);
    console.log("All assets loaded ✅");
    world = new World(canvas);
  } catch (err) {
    console.error("Asset loading failed ❌:", err);
  }
}
